sudo: false
language: php
php:
  - 5.6

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

install:
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
  - cd block && yarn && yarn run build
  - echo $PWD

before_deploy:
  echo $PWD

deploy:
  provider: script
  skip_cleanup: true
  script: cd .. bash .travis/deploy.sh
  on:
    branch: master
    php: 5.6
