sudo: false
language: php
php:
  - nightly
  - 5.6
  - 7.0
  - 7.1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true

install:
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
  - cd block && yarn && yarn run build

deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master
    php: 7.0
