sudo: false
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  apt: true
  yarn: true

install:
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - phpcs --standard=ruleset.xml --extensions=php -n -s .
  - cd block && yarn && yarn run build

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - zip $TRAVIS_BUILD_DIR${PLUGIN}-$TRAVIS_TAG.zip $TRAVIS_BUILD_DIR

deploy:
  provider: script
  skip_cleanup: true
  script: bash .travis/deploy.sh
  on:
    tags: true
    php: 5.6
