version: 2.0

references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_HOST: &WP_HOST
    easy-panorama.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    easy-panorama
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    leopeo

  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/easy-panorama

  workspace_root: &workspace_root
    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  install_subversion: &install_subversion
    run:
      name: Install subversion
      command: sudo apt-get install subversion

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install -n -o
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  php_quality:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run PHP code quality tests
          command: vendor/bin/phpcs --ignore=/vendor/ --standard=ruleset.xml --extensions=php -n -s .

  deploy_assets:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *install_subversion
      - run:
          name: Deploy assets to WordPress plugin directory
          command: bash .circleci/deploy-assets.sh

  deploy_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *install_subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: bash .circleci/deploy-plugin.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - php_quality:
          requires:
            - build
      - deploy_plugin:
          filters:
            branches:
              only:
                - master
          requires:
            - php_quality
